# Copyright 2026 Hot Path C++ Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "seqlock",
    hdrs = ["seqlock.h"],
    copts = ["-std=c++20"],
)

cc_test(
    name = "seqlock_test",
    srcs = ["seqlock_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":seqlock",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name = "seqlock_benchmark",
    srcs = ["seqlock_benchmark.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":seqlock",
        "@google_benchmark//:benchmark_main",
    ],
)

cc_library(
    name = "ebr",
    srcs = ["ebr.cc"],
    hdrs = ["ebr.h"],
    copts = ["-std=c++20"],
)

cc_library(
    name = "rcu_hash_map",
    hdrs = ["rcu_hash_map.h"],
    copts = ["-std=c++20"],
    deps = [
        ":ebr",
        "@abseil-cpp//absl/hash",
    ],
)

cc_test(
    name = "rcu_hash_map_test",
    srcs = ["rcu_hash_map_test.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":rcu_hash_map",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name = "rcu_hash_map_benchmark",
    srcs = ["rcu_hash_map_benchmark.cc"],
    copts = ["-std=c++20"],
    deps = [
        ":rcu_hash_map",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@google_benchmark//:benchmark_main",
    ],
)
